version: '3.8'
services:
  ai-room-cleaner:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CAMERA_ENTITY_ID=${CAMERA_ENTITY_ID}
      - SUPERVISOR_TOKEN=${SUPERVISOR_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - AI_MODEL=${AI_MODEL:-gemini-1.5-pro-latest}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped