version: '3.8'
services:
  backend:
    build:
      context: ./ai_room_cleaner
      dockerfile: backend/Dockerfile
    volumes:
      - ./ai_room_cleaner:/app/ai_room_cleaner
      - ./ai_room_cleaner/pyproject.toml:/app/pyproject.toml
      - ./logs:/app/logs
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
  frontend:
    build:
      context: ./ai_room_cleaner/frontend
    volumes:
      - ./ai_room_cleaner/frontend:/app
    ports:
      - "5173:5173"