version: '3.8'
services:
  backend:
    build:
      context: ./ai_room_cleaner
      dockerfile: backend/Dockerfile
    volumes:
      - ./ai_room_cleaner/backend:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./ai_room_cleaner/frontend
    volumes:
      - ./ai_room_cleaner/frontend:/app
    ports:
      - "5173:5173"