version: '3.8'
services:
  ai-room-cleaner:
    build:
      context: ./ai_room_cleaner
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./ai_room_cleaner/.env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped