# AI Room Cleaner Addon Configuration
name: "AI Room Cleaner"
version: "0.1.0"
slug: "ai_room_cleaner"
description: "An intelligent cleanliness assistant using a multimodal AI to keep your room tidy."
arch:
  - "aarch64"
  - "amd64"
  - "armv7"
init: false
panel_icon: "mdi:robot-vacuum"
ingress: true
ingress_port: 8000
startup: "application"
boot: "auto"
url: "https://github.com/hassio-addons/addon-ai-room-cleaner"
options:
  camera_entity: ""
  api_key: ""
  ai_model: "gemini-1.5-pro"
  update_frequency: 60
  supervisor_url: "http://supervisor/core/api"
  ai_prompt: >-
    Analyze this room image and identify any items that are out of place or contributing to messiness.
    For each item, describe what needs to be cleaned or organized.
    Return the output as a JSON array of strings, with each string being a specific cleaning task.
  cors_allowed_origins:
    - "*"
schema:
  camera_entity: "str"
  api_key: "password"
  ai_model: "str"
  update_frequency: "int(1,1440)"
  supervisor_url: "str"
  ai_prompt: "str"
  cors_allowed_origins: "list(str)"